route:
#  group_by: ['alertname']
#  group_wait: 30s
#  group_interval: 5m
#  repeat_interval: 1h
  receiver: 'email'
receivers:
  - name: 'email'
    email_configs:
      - to: xxxxxx@gmail.com
        from: xxxxxx@gmail.com
        smarthost: smtp.gmail.com:587
        auth_username: xxxxxx@gmail.com
        auth_identity: xxxxxx@gmail.com
        auth_password: xxxxxxxxxxxxxxxxxxxxxx
#inhibit_rules:
#  - source_match:
#      severity: 'critical'
#    target_match:
#      severity: 'warning'
#    equal: ['alertname', 'dev', 'instance']
