groups:
  - name: default
    rules:
      - alert: RequestRate
        expr: rate(http_server_requests_seconds_count{exception="None",method="GET",outcome="SUCCESS",status="200",uri="/api/v1/customer/{customerId}",}[5m]) > 0
        for: 1m
        labels:
          severity: high
        annotations:
          summary: Application receiving too many requests